name: Release Artifacts

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        enable_security: [true, false]
        include:
          - enable_security: true
            file_suffix: "-with-login"
          - enable_security: false
            file_suffix: ""
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: "17"
          distribution: "temurin"

      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          gradle-version: 8.12

      - name: Generate jar (With Security=${{ matrix.enable_security }})
        run: ./gradlew clean createExe
        env:
          DOCKER_ENABLE_SECURITY: ${{ matrix.enable_security }}
          STIRLING_PDF_DESKTOP_UI: false

      - name: Get version number
        id: versionNumber
        run: |
          VERSION=$(grep "^version =" build.gradle | awk -F'"' '{print $2}')
          echo "versionNumber=$VERSION" >> $GITHUB_OUTPUT

      - name: Rename binaries
        run: |
          cp ./build/launch4j/Stirling-PDF.exe ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.exe
          cp ./build/libs/Stirling-PDF-${{ steps.versionNumber.outputs.versionNumber }}.jar ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar

      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

      - name: Sign JAR with Cosign OIDC
        run: |
          cosign sign-blob \
            --yes \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar \
            > ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar.sig

      - name: Sign EXE with Cosign OIDC
        run: |
          cosign sign-blob  \
            --yes \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.exe \
            > ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.exe.sig

      - name: Generate Attestations for JAR
        run: |
          cosign attest-blob  \
            --predicate - \
            --yes \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar \
            > ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar.intoto.jsonl

      - name: Generate Attestations for EXE
        run: |
          cosign attest-blob  \
            --predicate - \
            --yes \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.exe \
            > ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.exe.intoto.jsonl

      - name: Upload binaries, attestations and signatures to release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          tag_name: v${{ steps.versionNumber.outputs.versionNumber }}
          files: |
            ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.*
            ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.*
