name: Swagger Endpoint Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "app/**"
      - "testing/swagger_endpoint_test.py"
      - ".github/workflows/swagger-endpoint-test.yml"
      - "build.gradle"
      - "settings.gradle"
      - "gradle/**"
      - "gradlew"
      - "gradlew.bat"
  push:
    branches:
      - master
    paths:
      - "app/**"
      - "testing/swagger_endpoint_test.py"
      - ".github/workflows/swagger-endpoint-test.yml"

jobs:
  swagger-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install --upgrade pip requests

      - name: Build Stirling PDF fat Docker image
        run: |
          docker build \
            --file Dockerfile.fat \
            --build-arg VERSION_TAG=${{ github.sha }} \
            --tag stirling-pdf-fat \
            .

      - name: Start Stirling PDF (Docker fat)
        run: |
          docker run -d \
            --name stirling-pdf-fat \
            -e DISABLE_ADDITIONAL_FEATURES=false \
            -p 8080:8080 \
            stirling-pdf-fat

      - name: Wait for application to be ready
        run: |
          for attempt in $(seq 1 40); do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/v1/api-docs || true)
            if [ "$status" != "000" ] && [ "$status" -lt 500 ]; then
              exit 0
            fi
            sleep 5
          done
          echo "Application did not become ready in time" >&2
          docker logs stirling-pdf-fat || true
          exit 1

      - name: Run Swagger endpoint tests
        run: python testing/swagger_endpoint_test.py --base-url http://localhost:8080

      - name: Collect server logs
        if: always()
        run: |
          docker logs stirling-pdf-fat > server.log 2>&1 || true

      - name: Stop and remove Stirling PDF container
        if: always()
        run: |
          docker stop stirling-pdf-fat || true
          docker rm stirling-pdf-fat || true

      - name: Upload server logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: swagger-server-logs
          path: server.log
          if-no-files-found: ignore
